# netlist_engine/cdl_writer.py
from .cdl_parser import NetlistIR, Instance, Subckt

class CDLWriter:
    def __init__(self, ir: NetlistIR, max_line_length: int = 80):
        self.ir = ir
        self.max_line_length = max_line_length

    def _wrap_line(self, tokens: list) -> str:
        """
        将 token 列表按最大行宽拼接，超过则使用 '+' 换行。
        """
        if not tokens:
            return ""
            
        lines = []
        current_line = tokens[0]
        
        for token in tokens[1:]:
            # +1 是因为有个空格
            if len(current_line) + 1 + len(token) > self.max_line_length:
                lines.append(current_line)
                current_line = "+ " + token
            else:
                current_line += " " + token
                
        lines.append(current_line)
        return "\n".join(lines)

    def _format_instance(self, inst_name: str, inst: Instance) -> str:
        """格式化单个器件/子电路实例"""
        tokens = [inst_name]
        tokens.extend(inst.ports)
        tokens.append(inst.ref_model)
        for k, v in inst.params.items():
            tokens.append(f"{k}={v}")
            
        return self._wrap_line(tokens)

    def write(self, output_path: str):
        """将 IR 序列化并写入文件"""
        with open(output_path, 'w') as f:
            f.write("* ==========================================\n")
            f.write("* AUTOMATICALLY GENERATED BY NETLIST ENGINE \n")
            f.write("* ==========================================\n\n")

            # 1. 遍历写入所有 Subckt
            for sub_name, subckt in self.ir.subckts.items():
                f.write(self._wrap_line([".SUBCKT", sub_name] + subckt.ports) + "\n")
                
                for inst_name, inst in subckt.instances.items():
                    f.write(self._format_instance(inst_name, inst) + "\n")
                    
                f.write(f".ENDS {sub_name}\n\n")

            # 2. 写入顶层调用的 Instance（如果有）
            if self.ir.top_level_instances:
                f.write("* TOP LEVEL INSTANCES\n")
                for inst_name, inst in self.ir.top_level_instances.items():
                    f.write(self._format_instance(inst_name, inst) + "\n")
